/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _layoutRouteImport } from './routes/__layout'
import { Route as _layoutIndexRouteImport } from './routes/__layout/index'
import { Route as _layoutSignInRouteImport } from './routes/__layout/sign-in'
import { Route as _layoutProfileRouteImport } from './routes/__layout/profile'
import { Route as _layoutAddDataRouteImport } from './routes/__layout/add-data'

const _layoutRoute = _layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutIndexRoute = _layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutSignInRoute = _layoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutProfileRoute = _layoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutAddDataRoute = _layoutAddDataRouteImport.update({
  id: '/add-data',
  path: '/add-data',
  getParentRoute: () => _layoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/add-data': typeof _layoutAddDataRoute
  '/profile': typeof _layoutProfileRoute
  '/sign-in': typeof _layoutSignInRoute
  '/': typeof _layoutIndexRoute
}
export interface FileRoutesByTo {
  '/add-data': typeof _layoutAddDataRoute
  '/profile': typeof _layoutProfileRoute
  '/sign-in': typeof _layoutSignInRoute
  '/': typeof _layoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__layout': typeof _layoutRouteWithChildren
  '/__layout/add-data': typeof _layoutAddDataRoute
  '/__layout/profile': typeof _layoutProfileRoute
  '/__layout/sign-in': typeof _layoutSignInRoute
  '/__layout/': typeof _layoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/add-data' | '/profile' | '/sign-in' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/add-data' | '/profile' | '/sign-in' | '/'
  id:
    | '__root__'
    | '/__layout'
    | '/__layout/add-data'
    | '/__layout/profile'
    | '/__layout/sign-in'
    | '/__layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _layoutRoute: typeof _layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/': {
      id: '/__layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _layoutIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/sign-in': {
      id: '/__layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof _layoutSignInRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/profile': {
      id: '/__layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof _layoutProfileRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/add-data': {
      id: '/__layout/add-data'
      path: '/add-data'
      fullPath: '/add-data'
      preLoaderRoute: typeof _layoutAddDataRouteImport
      parentRoute: typeof _layoutRoute
    }
  }
}

interface _layoutRouteChildren {
  _layoutAddDataRoute: typeof _layoutAddDataRoute
  _layoutProfileRoute: typeof _layoutProfileRoute
  _layoutSignInRoute: typeof _layoutSignInRoute
  _layoutIndexRoute: typeof _layoutIndexRoute
}

const _layoutRouteChildren: _layoutRouteChildren = {
  _layoutAddDataRoute: _layoutAddDataRoute,
  _layoutProfileRoute: _layoutProfileRoute,
  _layoutSignInRoute: _layoutSignInRoute,
  _layoutIndexRoute: _layoutIndexRoute,
}

const _layoutRouteWithChildren =
  _layoutRoute._addFileChildren(_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _layoutRoute: _layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
